#pragma once

static const char* coloredVertexShaderSource =
"#version 400\n"
"layout (location = 0) in vec3 aPos;\n"
"layout (location = 1) in vec4 aColor;\n"
"out vec4 vFragColor;\n"
"uniform mat4 viewProjection;\n"
"void main()\n"
"{\n"
"   gl_Position = viewProjection * vec4(aPos, 1.0);\n"
"   vFragColor = aColor;\n"
"}\0";

static const char* coloredFragmentShaderSource =
"#version 400\n"
"in vec4 vFragColor;\n"
"out vec4 outFragColor;\n"
"void main()\n"
"{\n"
"    outFragColor = vFragColor;\n"
"}\0";

static const char* texturedVertexShaderSource =
"#version 400\n"
"layout (location = 0) in vec3 aPos;\n"
"layout (location = 1) in vec2 aTexCoord;\n"
"out vec2 texCoord;\n"
"uniform mat4 viewProjection;\n"
"void main()\n"
"{\n"
"   gl_Position = viewProjection * vec4(aPos, 1.0);\n"
"   texCoord = aTexCoord;\n"
"}\0";

static const char* texturedFragmentShaderSource =
"#version 400\n"
"in vec2 texCoord;\n"
"out vec4 outFragColor;\n"
"uniform sampler2D textureMap;\n"
"void main()\n"
"{\n"
"    outFragColor = texture(textureMap, texCoord);\n"
"}\0";

static const char* textFragmentShaderSource =
"#version 400\n"
"in vec2 texCoord;\n"
"out vec4 outFragColor;\n"
"uniform sampler2D textureMap;\n"
"void main()\n"
"{\n"
"    float intensity = texture(textureMap, texCoord).r;\n"
"    if (intensity < 0.0001) discard;\n"
"    outFragColor = vec4(1, 1, 1, intensity);\n"
"}\0";

static const char* impostorVertexShaderSource =
"#version 400\n"
"layout(location = 0) in vec3 v_vertex;\n"
"layout(location = 1) in float v_size;\n"
"layout(location = 2) in vec4 v_color;\n"
"out float vSize;"
"out vec4 vColor;\n"
"void main()\n"
"{\n"
"    gl_Position = vec4(v_vertex, 1);\n"
"    vSize = v_size; \n"
"    vColor = v_color;\n"
"}\0";

// GLSL Shader to draw billboard sprites
// Feed in points containing
// x,y,z,radius
// r,g,b,a
static const char* impostorGeometryShaderSource =
"#version 400\n"
"layout(points) in;\n"
"layout(triangle_strip, max_vertices = 4) out;\n"
"in vec4 vColor[];\n"   // Color comes in from vertex shader
"in float vSize[];\n"   // Size too
"out Fragment{\n"      // Output data to fragment shader
"     smooth vec2 texCoord;\n"
"} fragment;\n"
"out vec4 spriteColor;\n"
"uniform mat4 projection;\n"
"uniform mat4 view;\n"
"void main()\n"
"{\n"
"    // Put us into screen space.\n"
"    vec4 pos = view * gl_in[0].gl_Position;\n"
"    float spriteRadius = vSize[0];\n"
"    spriteColor = vColor[0];\n"
"    vec4 fPos = projection * pos;\n"
"    gl_Position = pos; // Bottom left corner\n"
"    gl_Position.xy += vec2(-spriteRadius, -spriteRadius);\n"
"    gl_Position = projection * gl_Position;\n"
"    fragment.texCoord = vec2(0, 0);\n"
"    EmitVertex();\n"
"    gl_Position = pos; // Bottom right corner\n"
"    gl_Position.xy += vec2(spriteRadius, -spriteRadius);\n"
"    gl_Position = projection * gl_Position;\n"
"    fragment.texCoord = vec2(1, 0);\n"
"    EmitVertex();\n"
"    gl_Position = pos; // Top left corner\n"
"    gl_Position.xy += vec2(-spriteRadius, spriteRadius);\n"
"    gl_Position = projection * gl_Position;\n"
"    fragment.texCoord = vec2(0, 1);\n"
"    EmitVertex();\n"
"    gl_Position = pos; // Top right corner\n"
"    gl_Position.xy += vec2(spriteRadius, spriteRadius);\n"
"    gl_Position = projection * gl_Position;\n"
"    fragment.texCoord = vec2(1, 1);\n"
"    EmitVertex();\n"
"    EndPrimitive();\n"
"}\0";

static const char* impostorFragmentShaderSource =
"#version 400\n"
"out vec4 fragColor;\n"
"in Fragment{\n"
"    smooth vec2 texCoord;\n"
"} fragment;\n"
"in vec4 spriteColor;\n"
"uniform sampler2D textureMap;\n"
"void main()\n"
"{\n"
"    vec4 texColor = texture(textureMap, fragment.texCoord);\n"
"    if (texColor.a == 0.0) discard;\n"
"    fragColor = texColor * spriteColor;\n"
"}\0";

static const char* coloredInstanceVertexShaderSoure =
"#version 400\n"
"layout(location = 0) in vec3 v_vertex;\n"
"layout(location = 1) in vec4 v_color;\n"
"layout(location = 2) in vec3 instance_position;\n"
"layout(location = 3) in float instance_size;\n"
"layout(location = 4) in vec4 instance_rotation;\n"
"layout(location = 5) in vec4 instance_color;\n"
"uniform mat4 viewProjection;\n"
"out Fragment{\n"
"    vec4 iColor;\n"
"    smooth vec4 vColor;\n"
"} fragment;\n"
"mat3 mat3FromQuaternion(vec4 q)\n"
"{\n"
"    mat3 Result;\n"
"    float qxx = (q.x * q.x);\n"
"    float qyy = (q.y * q.y);\n"
"    float qzz = (q.z * q.z);\n"
"    float qxz = (q.x * q.z);\n"
"    float qxy = (q.x * q.y);\n"
"    float qyz = (q.y * q.z);\n"
"    float qwx = (q.w * q.x);\n"
"    float qwy = (q.w * q.y);\n"
"    float qwz = (q.w * q.z);\n"
"    Result[0][0] = 1 - 2 * (qyy + qzz);\n"
"    Result[0][1] = 2 * (qxy + qwz);\n"
"    Result[0][2] = 2 * (qxz - qwy);\n"
"    Result[1][0] = 2 * (qxy - qwz);\n"
"    Result[1][1] = 1 - 2 * (qxx + qzz);\n"
"    Result[1][2] = 2 * (qyz + qwx);\n"
"    Result[2][0] = 2 * (qxz + qwy);\n"
"    Result[2][1] = 2 * (qyz - qwx);\n"
"    Result[2][2] = 1 - 2 * (qxx + qyy);\n"
"    return Result;\n"
"}\n"
"void main()\n"
"{\n"
"    mat3 modelMatrix = mat3FromQuaternion(instance_rotation);\n"
"    vec3 vertex = modelMatrix * (v_vertex.xyz * instance_size);\n"
"    vertex += instance_position;\n"
"    gl_Position = viewProjection * vec4(vertex.xyz, 1.0);\n"
"    fragment.iColor = instance_color;\n"
"    fragment.vColor = v_color;\n"
"}\0";

static const char* coloredInstanceFragmentShaderSource =
"#version 400\n"
"layout(location = 0) out vec4 colorOut;\n"
"in Fragment{\n"
"    vec4 iColor;\n"
"    smooth vec4 vColor;\n"
"} fragment;\n"
"void main()\n"
"{\n"
"    colorOut = fragment.vColor * fragment.iColor;\n"
//"    colorOut = fragment.vColor;\n"
"}\0";

static const char* textured2DInstanceVertexShaderSoure =
"#version 400\n"
"layout(location = 0) in vec2 v_pos;\n"
"layout(location = 1) in vec2 v_texCoord;\n"
"layout(location = 2) in vec3 instance_position;\n"
"layout(location = 3) in float instance_size;\n"
"layout(location = 4) in vec4 instance_color;\n"
"uniform mat4 viewProjection;\n"
"out vec2 texCoord;\n"
"out vec4 color;\n"
"void main()\n"
"{\n"
"	texCoord = v_texCoord;\n"
"	color = instance_color;\n"
"	vec3 vertex = vec3(v_pos * instance_size, 0.0);\n"
"	vertex += instance_position.xyz;\n"
"	gl_Position = viewProjection * vec4(vertex.xyz, 1.0);\n"
"}\0";

static const char* textured2DInstanceFragmentShaderSource =
"#version 400\n"
"in vec2 texCoord;\n"
"in vec4 color;\n"
"out vec4 outFragColor;\n"
"uniform sampler2D textureMap;\n"
"void main()\n"
"{\n"
"	vec4 texColor = texture(textureMap, texCoord);\n"
"   outFragColor = texColor * color;\n"
"}\0";

static const char* texturedPBRVertexShaderSource =
"#version 400\n"
"layout(location = 0) in vec3 v_vertex;\n"
"layout(location = 1) in vec3 v_normal;\n"
"layout(location = 2) in vec3 v_tangent;\n"
"layout(location = 3) in vec2 v_uv;\n"
"uniform mat4 viewProjection;\n"
"out Fragment{\n"
"    smooth vec2 uv;\n"
"    smooth float depth;\n"
"    smooth vec3 fragPos;\n"
"    mat3 tbn;\n"
"} fragment;\n"
"void main()\n"
"{\n"
"    vec4 vertex = vec4(v_vertex.xyz, 1.0);\n"
"    gl_Position = viewProjection * vertex;\n"
"    fragment.uv = v_uv;\n"
"    fragment.depth = gl_Position.z;\n"
"    fragment.fragPos = vertex.xyz;\n"
"    mat3 modelMatrix = mat3(1.0);\n"
"    vec3 bitangent = cross(v_normal, v_tangent);\n"
"    fragment.tbn = mat3(normalize(vec3(modelMatrix * v_tangent)),\n"
"        normalize(vec3(modelMatrix * bitangent)),\n"
"        normalize(vec3(modelMatrix * v_normal)));\n"
"}\0";

static const char* texturedPBRFragmentShaderSource =
"#version 400\n"
"layout(location = 0) out vec4 albedoOut;\n"
"layout(location = 1) out vec4 materialOut;\n"
"layout(location = 2) out vec3 normalOut;\n"
"layout(location = 3) out float depthOut;\n"
"uniform sampler2D albedoTexture;\n"
"uniform sampler2D normalTexture;\n"
"uniform sampler2D metalnessTexture;\n"
"uniform sampler2D roughnessTexture;\n"
"uniform sampler2D displacementTexture;\n"
"uniform sampler2D emissiveTexture;\n"
"uniform vec3 cameraPosition;\n"
"in Fragment{\n"
"    smooth vec2 uv;\n"
"    smooth float depth;\n"
"    smooth vec3 fragPos;\n"
"    mat3 tbn;\n"
"} fragment;\n"
"#define USE_DISPLACEMENT\n"
"float find_intersection(vec2 dp, vec2 ds)\n"
"{\n"
"    const int linear_steps = 10;\n"
"    const int binary_steps = 5;\n"
"    float depth_step = 1.0 / linear_steps;\n"
"    float size = depth_step;\n"
"    float depth = 1.0;\n"
"    float best_depth = 1.0;\n"
"    for (int i = 0; i < linear_steps - 1; ++i) {\n"
"        depth -= size;\n"
"        float t = texture(displacementTexture, dp + ds * depth).r;\n"
"        if (depth >= 1.0 - t)\n"
"            best_depth = depth;\n"
"    }\n"
"    depth = best_depth - size;\n"
"    for (int i = 0; i < binary_steps; ++i) {\n"
"        size *= 0.5;\n"
"        float t = texture(displacementTexture, dp + ds * depth).r;\n"
"        if (depth >= 1.0 - t) {\n"
"            best_depth = depth;\n"
"            depth -= 2 * size;\n"
"        }\n"
"        depth += size;\n"
"    }\n"
"    return best_depth;\n"
"}\n"
"void main()\n"
"{\n"
"    vec2 uv = fragment.uv;\n"
"#ifdef USE_DISPLACEMENT\n"
"    float height = texture(displacementTexture, uv).r;\n"
"    if (height < 1.0)\n"
"    {\n"
"        float depth = 0.0025;\n"
"        vec3 eview = cameraPosition - fragment.fragPos;\n"
"        vec3 tview = normalize(vec3(dot(eview, fragment.tbn[0]),\n"
"            dot(eview, fragment.tbn[1]),\n"
"            dot(eview, fragment.tbn[2])));\n"
"        vec2 ds = tview.xy * depth;\n"
"        float dist = find_intersection(uv, ds);\n"
"        uv += dist * ds;\n"
"        //float texel = 1.0 / 4096.0;\n"
"        //vec2 maxUV = fragment.material + vec2(1.0 / 16.0);\n"
"        //if (uv.x > maxUV.x || uv.y > maxUV.y ||\n"
"            //uv.x < fragment.material.x || uv.y < fragment.material.y)\n"
"            //discard;\n"
"        //float divisor = 1.0 / 16.0;\n"
"        //uv.x = fragment.material.x + mod(uv.x, divisor);\n"
"        //uv.y = fragment.material.y + mod(uv.y, divisor);\n"
"    }\n"
"#endif\n"
"    vec4 albedo = texture(albedoTexture, uv);\n"
"    vec3 normal = (texture(normalTexture, uv).rgb * 2.0) - 1.0;\n"
"    float metalness = texture(metalnessTexture, uv).r;\n"
"    float roughness = texture(roughnessTexture, uv).r;\n"
"    float emissive = texture(emissiveTexture, uv).r;\n"
"    albedoOut = vec4(albedo.rgb, 1.0);\n"
"    materialOut = vec4(roughness, metalness, emissive, 1.0);\n"
"    normalOut = (normalize(fragment.tbn * normal) + 1.0) * 0.5;\n"
"    depthOut = fragment.depth;// + (1.0-displacement);\n"
"}\0";

static const char* instancedPBRVertexShaderSoure =
"#version 400\n"
"layout(location = 0) in vec3 v_vertex;\n"
"layout(location = 1) in vec3 v_normal;\n"
"layout(location = 2) in vec3 v_tangent;\n"
"layout(location = 3) in vec2 v_uv;\n"
"layout(location = 4) in vec3 instance_position;\n"
"layout(location = 5) in vec4 instance_rotation;\n"
"layout(location = 6) in vec3 instance_scale;\n"
"uniform mat4 viewProjection;\n"
"out Fragment{\n"
"    smooth vec2 uv;\n"
"    smooth float depth;\n"
"    smooth vec3 fragPos;\n"
"    mat3 tbn;\n"
"} fragment;\n"
"mat3 mat3FromQuaternion(vec4 q)\n"
"{\n"
"    mat3 Result;\n"
"    float qxx = (q.x * q.x);\n"
"    float qyy = (q.y * q.y);\n"
"    float qzz = (q.z * q.z);\n"
"    float qxz = (q.x * q.z);\n"
"    float qxy = (q.x * q.y);\n"
"    float qyz = (q.y * q.z);\n"
"    float qwx = (q.w * q.x);\n"
"    float qwy = (q.w * q.y);\n"
"    float qwz = (q.w * q.z);\n"
"    Result[0][0] = 1 - 2 * (qyy + qzz);\n"
"    Result[0][1] = 2 * (qxy + qwz);\n"
"    Result[0][2] = 2 * (qxz - qwy);\n"
"    Result[1][0] = 2 * (qxy - qwz);\n"
"    Result[1][1] = 1 - 2 * (qxx + qzz);\n"
"    Result[1][2] = 2 * (qyz + qwx);\n"
"    Result[2][0] = 2 * (qxz + qwy);\n"
"    Result[2][1] = 2 * (qyz - qwx);\n"
"    Result[2][2] = 1 - 2 * (qxx + qyy);\n"
"    return Result;\n"
"}\n"
"void main()\n"
"{\n"
"    mat3 modelMatrix = mat3FromQuaternion(instance_rotation);\n"
"    vec3 vertex = modelMatrix * (v_vertex * instance_scale);\n"
"    vertex += instance_position;\n"
"    gl_Position = viewProjection * vec4(vertex, 1.0);\n"
"    fragment.uv = v_uv;\n"
"    fragment.depth = gl_Position.z;\n"
"    fragment.fragPos = vertex.xyz;\n"
"    vec3 bitangent = cross(v_normal, v_tangent);\n"
"    fragment.tbn = mat3(normalize(vec3(modelMatrix * v_tangent)),\n"
"        normalize(vec3(modelMatrix * bitangent)),\n"
"        normalize(vec3(modelMatrix * v_normal)));\n"
"}\0";

static const char* lightPassVertexShaderSource =
"#version 400\n"
"layout(location = 0) in vec3 vVertex;\n"
"layout(location = 1) in vec2 vTex;\n"
"layout(location = 2) in vec3 vFrustum;\n"
"out vec2 texCoord;\n"
"out vec3 viewRay;\n"
"void main(void)\n"
"{\n"
"	texCoord = vTex;    // Interpolated texture coordinates (0...1)\n"
"	viewRay = vFrustum; // Interpolated ray to frustum far plane\n"
"	gl_Position.xyz = vVertex * 2.0;\n"
"	gl_Position.w = 1;\n"
"}\0";

static const char* lightPassFragmentShaderSource =
"#version 400\n"
"layout(location = 0) out vec4 colorOut;\n"
"uniform sampler2D albedoMap;\n"
"uniform sampler2D materialMap;\n"
"uniform sampler2D normalMap;\n"
"uniform sampler2D depthMap;\n"
"uniform vec3 camPos;\n"
"uniform float reflectionSize;\n"
"uniform vec3 reflectionPos;\n"
"uniform vec2 depthParameter;\n"
"uniform vec4 lightPosition;        // World X,Y,Z, Radius\n"
"uniform vec4 lightColor;           // RGB and ambient\n"
"uniform vec3 lightAttenuation;     // Constant, Linear, Quadratic\n"
"uniform vec3 lightSpotDirection;   // Spot light direction\n"
"uniform float lightSpotCutoff;		// For spot lights < 90.0\n"
"uniform float lightSpotExponent;	// Spot light exponent\n"
"uniform float nearDepth;\n"
"uniform float farDepth;\n"
"uniform bool renderFog;\n"
"uniform float fogDensity = 1.0;         // Global fog density\n"
"uniform float fogHeightFalloff = 0.5;   // Fog height falloff parameter\n"
"uniform float fogExtinctionFalloff = 20.0;\n"
"uniform float fogInscatteringFalloff = 20.0;\n"
"uniform vec3 fogColor = vec3(0.5, 0.6, 0.8);\n"
"in vec2 texCoord;\n"
"in vec3 viewRay;\n"
"float getLightAttenuation(vec3 lightDir, float dist)\n"
"{\n"
"    float attenuation = 1.0 - (lightAttenuation.x +\n"
"        (lightAttenuation.y * dist) +\n"
"        (lightAttenuation.z * dist * dist));\n"
"    attenuation = clamp(attenuation, 0.0, 1.0);\n"
"    if (lightSpotCutoff > 90.0)\n"
"    {\n"
"        return attenuation;\n"
"    }\n"
"    // spotlight\n"
"    float clampedCosine = clamp(dot(-lightDir, normalize(lightSpotDirection)), 0.0, 1.0);\n"
"    if (clampedCosine < cos(radians(lightSpotCutoff)))\n"
"    {\n"
"        return 0.0; // outside of spotlight cone\n"
"    }\n"
"    return attenuation * pow(clampedCosine, lightSpotExponent);\n"
"}\n"
"void main(void)\n"
"{\n"
"    // Read depth and normal values from buffer\n"
"    float depth = texture(depthMap, texCoord).r;\n"
"    // interpolating normals will change the length of the normal, so renormalize the normal\n"
"    vec3 normal = normalize((texture(normalMap, texCoord).xyz * 2.0) - 1.0);\n"
"    // Material properties\n"
"    vec4 albedo = texture(albedoMap, texCoord);\n"
"    vec4 material = texture(materialMap, texCoord);\n"
"    float roughness = material.r;\n"
"    // float metalness = material.g;\n"
"    // Linearize depth\n"
"    float depthLinear = -depthParameter.y / (depthParameter.x - depth);\n"
"    float depthProjected = depthLinear / (farDepth - nearDepth);\n"
"    // Get distance to pixel in world coordinates\n"
"    vec3 pixelDistance = viewRay * depthProjected;\n"
"    // Project pixel world position\n"
"    vec3 pixelWorldPos = camPos + pixelDistance;\n"
"    vec3 viewDir = normalize(camPos - pixelWorldPos);\n"
"    vec3 lightToFragment = lightPosition.xyz - pixelWorldPos;\n"
"    vec3 lightDir = normalize(lightToFragment);\n"
"    float attenuation = 1.0;\n"
"    if (lightPosition.w == 0.0) // Directional light\n"
"    {\n"
"        lightDir = normalize(vec3(lightPosition.xyz));\n"
"    }\n"
"    else // Point or spot light (or other kind of light)\n"
"    {\n"
"        float dist = length(lightToFragment);\n"
"        if (dist > lightPosition.w) discard;\n"
"        attenuation = getLightAttenuation(lightDir, dist / lightPosition.w);\n"
"        //attenuation = getLightAttenuation(lightDir, dist);\n"
"    }\n"
"    vec3 reflectDir = reflect(-lightDir, normal);\n"
"    // Compute light contribution\n"
"    float ambientAmount = lightColor.a;\n"
"    float diffuseAmount = max(dot(normal, lightDir), 0.0) * attenuation;\n"
"    float specularAmount = pow(max(dot(viewDir, reflectDir), 0.0), roughness * 32.0);\n"
"    vec3 light = (ambientAmount + diffuseAmount + specularAmount) * lightColor.rgb;\n"
"    colorOut.rgb = albedo.rgb * light;\n"
"}\0";

static const char* lightPass2DFragmentShaderSource =
"#version 330 core\n"
"in vec2 texCoord;\n"
"out vec4 outFragColor;\n"
"uniform sampler2D textureMap;\n"
"uniform sampler2D lightMap;\n"
"void main()\n"
"{\n"
"    vec4 lightColor = texture(lightMap, texCoord);\n"
"    outFragColor = lightColor * texture(textureMap, texCoord);\n"
"}\0";